### PR TITLE
Fix Grade Regex Bug with Storage 

### LINKED ISSUE #102: (BUG) Assignment not stored properly
Stored grade of 100 does not load back into the App properly 
- 100 is saved as 100.0, which does not meet the validation regex when loading back into the app

### PR DESCRIPTION
**Pull request by gnoossk**
Closes #102 

Assignment's Grade's regex did not accept 100.0, 100.00.., etc which caused bugs when loading 100.0 from storage back into assignments. 

Added small change to regex to allow for this

### CODE REVIEW

File: src/main/java/seedu/address/model/assignment/Grade.java [hunk 1]
```diff
@@ -16,7 +16,7 @@ public class Grade {
             "Grade should be a decimal number not between 0 and 100 (inclusive) "
             + "OR null if not graded";
 
-    public static final String VALIDATION_REGEX = "[0-9]{1,2}\\.[0-9]*|NULL|[0-9]{1,2}|100";
+    public static final String VALIDATION_REGEX = "[0-9]{1,2}\\.[0-9]*|NULL|[0-9]{1,2}|100(\\.0*)?";
```
Comment (natlv) [inline src/main/java/seedu/address/model/assignment/Grade.java:19]: LGTM

**Review by Edsel-Tan — APPROVED** [review]
Nice spot! LGTM.
